spring.application.name=calvario
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=mision_calvario;trustServerCertificate=true
spring.datasource.username=admin
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Roles disponibles: ADMIN, AP, PD, PASTOR

jwt.secret=mision-calvario-secret-key-2025-muy-larga-para-seguridad
jwt.expiration=86400000

server.port=8080